// EN: Variable names have been checked and replaced with self-descriptive names
// CZ: Názvy proměnných byly zkontrolovány a nahrazeny samopopisnými názvy
global using System.Collections.Generic;
global using System.Reflection;
global using System;
global using System.Linq;
global using System.Text;
global using System.IO;
global using System.Data;
global using System.Text.RegularExpressions;
global using System.Collections.Specialized;
global using System.Net;
global using Diacritics.Extensions;
global using System.Collections;
global using SunamoUri._sunamo.SunamoArgs;
global using SunamoUri._sunamo.SunamoCollectionsGeneric;
global using SunamoUri._sunamo.SunamoDictionary;
global using SunamoUri._sunamo.SunamoStringParts;
global using SunamoUri._sunamo.SunamoStringReplace;
global using SunamoUri._sunamo.SunamoStringSubstring;
global using SunamoUri._sunamo.SunamoStringTrim;
global using SunamoUri._sunamo.SunamoExceptions;
global using SunamoUri._sunamo.SunamoLang.SunamoI18N;
global using SunamoUri._sunamo.SunamoValues.Values;
global using Case.NET;
global using System.Diagnostics;
global using SunamoUri._sunamo.SunamoString;
global using System.Diagnostics.CodeAnalysis;
global using SunamoUri;
global using SunamoUri._sunamo;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
